-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS franchise.franquicia
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status integer NOT NULL,
    CONSTRAINT franquicia_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS franchise.producto
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status integer NOT NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS franchise.sucursal
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status integer NOT NULL,
    franquicia_id integer NOT NULL,
    CONSTRAINT sucursal_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS franchise.sucursal_x_producto
(
    sucursal_id integer NOT NULL,
    producto_id integer NOT NULL,
    stock bigint NOT NULL,
    id serial NOT NULL,
    CONSTRAINT sucursal_x_producto_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS franchise.sucursal
    ADD CONSTRAINT fk_sucursal_franquicia FOREIGN KEY (franquicia_id)
    REFERENCES franchise.franquicia (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_sucursal_franquicia
    ON franchise.sucursal(franquicia_id);


ALTER TABLE IF EXISTS franchise.sucursal_x_producto
    ADD CONSTRAINT fk_sucursal_has_producto_producto FOREIGN KEY (producto_id)
    REFERENCES franchise.producto (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_sucursal_x_producto_producto
    ON franchise.sucursal_x_producto(producto_id);


ALTER TABLE IF EXISTS franchise.sucursal_x_producto
    ADD CONSTRAINT fk_sucursal_has_producto_sucursal FOREIGN KEY (sucursal_id)
    REFERENCES franchise.sucursal (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_sucursal_x_producto_sucursal
    ON franchise.sucursal_x_producto(sucursal_id);

END;